// ==========================================================================
// ReportParameterGraduationService
// Generates a static C# source file from a ReportParameterDefinition,
// allowing users to "graduate" from dynamic definitions to compiled code.
// ==========================================================================

using System.Text;
using XafReportParametersObjects.Module.BusinessObjects;

namespace XafReportParametersObjects.Module.Services;

public static class ReportParameterGraduationService
{
    public static string GenerateGraduationSource(ReportParameterDefinition definition)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// ==========================================================================");
        sb.AppendLine($"// Graduated from dynamic ReportParameterDefinition: {definition.GeneratedClassName}");
        sb.AppendLine($"// Report: {definition.Report?.DisplayName ?? "(unknown)"}");
        sb.AppendLine($"// Generated: {DateTime.Now:yyyy-MM-dd HH:mm}");
        sb.AppendLine("//");
        sb.AppendLine("// This file was generated by the ReportParameterObject generator.");
        sb.AppendLine("// You can safely modify GetCriteria(), GetSorting(), and add validation.");
        sb.AppendLine("// ==========================================================================");
        sb.AppendLine();
        sb.AppendLine("using DevExpress.ExpressApp;");
        sb.AppendLine("using DevExpress.ExpressApp.DC;");
        sb.AppendLine("using DevExpress.ExpressApp.ReportsV2;");
        sb.AppendLine("using DevExpress.Data.Filtering;");
        sb.AppendLine("using DevExpress.Xpo.DB;");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine();
        sb.AppendLine("namespace XafReportParametersObjects.Module.ReportParameters;");
        sb.AppendLine();
        sb.AppendLine("[DomainComponent]");
        sb.AppendLine($"public class {definition.GeneratedClassName} : ReportParametersObjectBase");
        sb.AppendLine("{");

        sb.AppendLine($"    public {definition.GeneratedClassName}(IObjectSpaceCreator provider) : base(provider)");
        sb.AppendLine("    {");
        sb.AppendLine("    }");
        sb.AppendLine();

        foreach (var field in definition.Fields)
        {
            var isLookup = !string.IsNullOrEmpty(field.ReferencedTypeName);
            var typeName = isLookup ? field.ReferencedTypeName! : GetSimpleTypeName(field.ClrTypeName);

            if (isLookup)
            {
                sb.AppendLine($"    public {typeName}? {field.PropertyName} {{ get; set; }}");
            }
            else
            {
                var defaultSuffix = field.ClrTypeName == "System.String" ? " = string.Empty;" : "";
                sb.AppendLine($"    public {typeName} {field.PropertyName} {{ get; set; }}{defaultSuffix}");
            }
        }

        sb.AppendLine();

        sb.AppendLine("    protected override IObjectSpace CreateObjectSpace()");
        sb.AppendLine("    {");
        sb.AppendLine("        // TODO: Change the type argument to match your report's data source type");
        sb.AppendLine("        return objectSpaceCreator.CreateObjectSpace(typeof(object));");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    public override CriteriaOperator GetCriteria()");
        sb.AppendLine("    {");
        sb.AppendLine("        var criteria = new List<CriteriaOperator>();");
        sb.AppendLine();

        foreach (var field in definition.Fields.Where(f => f.IncludeInCriteria))
        {
            var isLookup = !string.IsNullOrEmpty(field.ReferencedTypeName);
            var path = field.CriteriaPropertyPath ?? field.PropertyName;

            if (isLookup)
            {
                sb.AppendLine($"        if ({field.PropertyName} is not null)");
                sb.AppendLine($"            criteria.Add(CriteriaOperator.Parse(\"{path} = ?\", {field.PropertyName}.ID));");
            }
            else if (field.ClrTypeName == "System.String")
            {
                sb.AppendLine($"        if (!string.IsNullOrEmpty({field.PropertyName}))");
                sb.AppendLine($"            criteria.Add(CriteriaOperator.Parse(\"{path} = ?\", {field.PropertyName}));");
            }
            else if (field.ClrTypeName == "System.DateTime")
            {
                sb.AppendLine($"        if ({field.PropertyName} != default)");
                sb.AppendLine($"            criteria.Add(CriteriaOperator.Parse(\"{path} >= ?\", {field.PropertyName}));");
            }
            else
            {
                sb.AppendLine($"        criteria.Add(CriteriaOperator.Parse(\"{path} = ?\", {field.PropertyName}));");
            }
        }

        sb.AppendLine();
        sb.AppendLine("        return CriteriaOperator.And(criteria);");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    public override SortProperty[] GetSorting()");
        sb.AppendLine("    {");
        sb.AppendLine("        // TODO: Add sorting properties as needed");
        sb.AppendLine("        return Array.Empty<SortProperty>();");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GetSimpleTypeName(string clrTypeName) => clrTypeName switch
    {
        "System.String" => "string",
        "System.Int32" => "int",
        "System.Int64" => "long",
        "System.Decimal" => "decimal",
        "System.Double" => "double",
        "System.Single" => "float",
        "System.Boolean" => "bool",
        "System.DateTime" => "DateTime",
        "System.Guid" => "Guid",
        _ => clrTypeName
    };
}
